# app/config/config.yml

#...

parameters: 
    locale: fr
    # ...
framework:
    # On définit la langue par défaut pour le service de traduction
    # Ce qui n'est pas disponible dans la locale de l'utilisateur sera affiché dans celle spécifiée ici
    translator: { fallbacks: ['%locale%'] }

    # ...
    
    # On initialise la locale de requête, celle par défaut pour l'internaute arrivant pour la toute première fois sur mon site
    default_locale: '%locale%'
 