# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.validator.antiflood:                                     # Le nom du service
        class: OC\PlatformBundle\Validator\AntifloodValidator            # La classe du service, ici mon validateur est créé
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]    # Les données qu'on injecte dans le service: la reqûete et EntityMan.
        tags: 
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }   # C'est avec l'alias qu'on retrouvera le service
        
        
        